// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: apps/blogger/pb/blogger.proto

package blogger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blogger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 博客名
	// @gotags: bson:"blog_name" json:"blog_name" validate:"required"
	BlogName string `protobuf:"bytes,1,opt,name=blog_name,json=blogName,proto3" json:"blog_name" bson:"blog_name" validate:"required"`
	// 子标题
	// @gotags: bson:"sub_title" json:"sub_title" validate:"required"
	SubTitle string `protobuf:"bytes,2,opt,name=sub_title,json=subTitle,proto3" json:"sub_title" bson:"sub_title" validate:"required"`
	// 备案号
	// @gotags: bson:"bei_an" json:"bei_an" validate:"required"
	BeiAn string `protobuf:"bytes,3,opt,name=bei_an,json=beiAn,proto3" json:"bei_an" bson:"bei_an" validate:"required"`
	// 底部title
	// @gotags: bson:"b_title" json:"b_title" validate:"required"
	BTitle string `protobuf:"bytes,4,opt,name=b_title,json=bTitle,proto3" json:"b_title" bson:"b_title" validate:"required"`
	// 版权声明
	// @gotags: bson:"copyright" json:"copyright" validate:"required"
	Copyright string `protobuf:"bytes,5,opt,name=copyright,proto3" json:"copyright" bson:"copyright" validate:"required"`
	// 专题说明
	// @gotags: bson:"series_desc" json:"series_desc" validate:"required"
	SeriesDesc string `protobuf:"bytes,6,opt,name=series_desc,json=seriesDesc,proto3" json:"series_desc" bson:"series_desc" validate:"required"`
	// 归档说明
	// @gotags: bson:"archives_desc" json:"archives_desc" validate:"required"
	ArchivesDesc string `protobuf:"bytes,7,opt,name=archives_desc,json=archivesDesc,proto3" json:"archives_desc" bson:"archives_desc" validate:"required"`
}

func (x *Blogger) Reset() {
	*x = Blogger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_blogger_pb_blogger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blogger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blogger) ProtoMessage() {}

func (x *Blogger) ProtoReflect() protoreflect.Message {
	mi := &file_apps_blogger_pb_blogger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blogger.ProtoReflect.Descriptor instead.
func (*Blogger) Descriptor() ([]byte, []int) {
	return file_apps_blogger_pb_blogger_proto_rawDescGZIP(), []int{0}
}

func (x *Blogger) GetBlogName() string {
	if x != nil {
		return x.BlogName
	}
	return ""
}

func (x *Blogger) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Blogger) GetBeiAn() string {
	if x != nil {
		return x.BeiAn
	}
	return ""
}

func (x *Blogger) GetBTitle() string {
	if x != nil {
		return x.BTitle
	}
	return ""
}

func (x *Blogger) GetCopyright() string {
	if x != nil {
		return x.Copyright
	}
	return ""
}

func (x *Blogger) GetSeriesDesc() string {
	if x != nil {
		return x.SeriesDesc
	}
	return ""
}

func (x *Blogger) GetArchivesDesc() string {
	if x != nil {
		return x.ArchivesDesc
	}
	return ""
}

var File_apps_blogger_pb_blogger_proto protoreflect.FileDescriptor

var file_apps_blogger_pb_blogger_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77, 0x65, 0x6f, 0x70, 0x73, 0x2e, 0x73, 0x70, 0x61, 0x72,
	0x6b, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x22, 0xd7, 0x01, 0x0a, 0x07, 0x42, 0x6c,
	0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x67, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x62, 0x65, 0x69, 0x5f, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x65, 0x69, 0x41, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x70, 0x79, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x70, 0x79, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x44, 0x65, 0x73, 0x63, 0x12, 0x23,
	0x0a, 0x0d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x73, 0x44,
	0x65, 0x73, 0x63, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77, 0x65, 0x6f, 0x70, 0x73, 0x2f, 0x73, 0x70, 0x61,
	0x72, 0x6b, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_blogger_pb_blogger_proto_rawDescOnce sync.Once
	file_apps_blogger_pb_blogger_proto_rawDescData = file_apps_blogger_pb_blogger_proto_rawDesc
)

func file_apps_blogger_pb_blogger_proto_rawDescGZIP() []byte {
	file_apps_blogger_pb_blogger_proto_rawDescOnce.Do(func() {
		file_apps_blogger_pb_blogger_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_blogger_pb_blogger_proto_rawDescData)
	})
	return file_apps_blogger_pb_blogger_proto_rawDescData
}

var file_apps_blogger_pb_blogger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_blogger_pb_blogger_proto_goTypes = []interface{}{
	(*Blogger)(nil), // 0: cloudweops.spark.blogger.Blogger
}
var file_apps_blogger_pb_blogger_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_blogger_pb_blogger_proto_init() }
func file_apps_blogger_pb_blogger_proto_init() {
	if File_apps_blogger_pb_blogger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_blogger_pb_blogger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blogger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_blogger_pb_blogger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_blogger_pb_blogger_proto_goTypes,
		DependencyIndexes: file_apps_blogger_pb_blogger_proto_depIdxs,
		MessageInfos:      file_apps_blogger_pb_blogger_proto_msgTypes,
	}.Build()
	File_apps_blogger_pb_blogger_proto = out.File
	file_apps_blogger_pb_blogger_proto_rawDesc = nil
	file_apps_blogger_pb_blogger_proto_goTypes = nil
	file_apps_blogger_pb_blogger_proto_depIdxs = nil
}
