// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: apps/blogger/pb/rpc.proto

package blogger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	CreateBlogger(ctx context.Context, in *CreateBloggerRequest, opts ...grpc.CallOption) (*CreateBloggerResponse, error)
	DescribeBlogger(ctx context.Context, in *DescribeBloggerRequest, opts ...grpc.CallOption) (*DescribeBloggerResponse, error)
	UpdateBlogger(ctx context.Context, in *UpdateBloggerRequest, opts ...grpc.CallOption) (*UpdateBloggerResponse, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) CreateBlogger(ctx context.Context, in *CreateBloggerRequest, opts ...grpc.CallOption) (*CreateBloggerResponse, error) {
	out := new(CreateBloggerResponse)
	err := c.cc.Invoke(ctx, "/cloudweops.spark.blogger.RPC/CreateBlogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) DescribeBlogger(ctx context.Context, in *DescribeBloggerRequest, opts ...grpc.CallOption) (*DescribeBloggerResponse, error) {
	out := new(DescribeBloggerResponse)
	err := c.cc.Invoke(ctx, "/cloudweops.spark.blogger.RPC/DescribeBlogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) UpdateBlogger(ctx context.Context, in *UpdateBloggerRequest, opts ...grpc.CallOption) (*UpdateBloggerResponse, error) {
	out := new(UpdateBloggerResponse)
	err := c.cc.Invoke(ctx, "/cloudweops.spark.blogger.RPC/UpdateBlogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	CreateBlogger(context.Context, *CreateBloggerRequest) (*CreateBloggerResponse, error)
	DescribeBlogger(context.Context, *DescribeBloggerRequest) (*DescribeBloggerResponse, error)
	UpdateBlogger(context.Context, *UpdateBloggerRequest) (*UpdateBloggerResponse, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) CreateBlogger(context.Context, *CreateBloggerRequest) (*CreateBloggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlogger not implemented")
}
func (UnimplementedRPCServer) DescribeBlogger(context.Context, *DescribeBloggerRequest) (*DescribeBloggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeBlogger not implemented")
}
func (UnimplementedRPCServer) UpdateBlogger(context.Context, *UpdateBloggerRequest) (*UpdateBloggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlogger not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_CreateBlogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBloggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).CreateBlogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudweops.spark.blogger.RPC/CreateBlogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).CreateBlogger(ctx, req.(*CreateBloggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_DescribeBlogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeBloggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).DescribeBlogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudweops.spark.blogger.RPC/DescribeBlogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).DescribeBlogger(ctx, req.(*DescribeBloggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_UpdateBlogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBloggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).UpdateBlogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudweops.spark.blogger.RPC/UpdateBlogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).UpdateBlogger(ctx, req.(*UpdateBloggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudweops.spark.blogger.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlogger",
			Handler:    _RPC_CreateBlogger_Handler,
		},
		{
			MethodName: "DescribeBlogger",
			Handler:    _RPC_DescribeBlogger_Handler,
		},
		{
			MethodName: "UpdateBlogger",
			Handler:    _RPC_UpdateBlogger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/blogger/pb/rpc.proto",
}
